### ISSUE TITLE
Option tag block overflow mobile view on google chrome inspect view

### ISSUE THREAD

**Issue by sahanpasindu** [BootstrapDash/PurpleAdmin-Free-Admin-Template#1]
I'm using this free template for a my project 
I have been populated select tag option using database. But when i view it in mobile view using Google chrome inspect view the design block of option tag go beyond the screen size 

Let me show what i am talking here 
![option](https://user-images.githubusercontent.com/26884480/41599580-4615541a-73f1-11e8-80ee-54b5ce7b0641.png)
This is only show when i check it as a mobile view. And i am not add any extra class for option tag i am using original classes

**Comment by fathimalinsak** [comment]
The behavior occurs only while using developer tools. It is rendered correctly when viewed in the actual mobile device and with screen resizing in desktop view.
