### ISSUE TITLE
Unable to edit css 

### ISSUE THREAD

**Issue by wprincearora** [BootstrapDash/PurpleAdmin-Free-Admin-Template#2]
I tried editing css but it didn't work . I am newbies to scss and gulp.js concept for designing . I did a lot of research but found nothing on how to compile scss to css again . Please Help me edit css

**Comment by vitorregisrr** [comment]
Hey prince! Do you still need help?

**Comment by max26292** [comment]
@@ you can use visual code and glup ^^ please you google search

**Comment by bootstrapdash-team** [comment]
@wwwprincearora Closing the issue due to inactive status for long time. please reopen this if you still face issues.
