### ISSUE TITLE
Need multiple theme options.

### ISSUE THREAD

**Issue by rakeshmali** [BootstrapDash/PurpleAdmin-Free-Admin-Template#5]
Hi I need scss variables where it will possible to change css by putting one color theme class in body and it will change whole the projectr according to it.

**Comment by bootstrapdash-team** [comment]
@rakeshmali Currently, we do not have an option to switch the entire theme by adding a class to the body, but you can change the while theme of the template by modifiying theme colors in variables.scss and recompiling.
