### ISSUE TITLE
Can we remove footer?

### ISSUE THREAD

**Issue by patelmanthan777** [BootstrapDash/PurpleAdmin-Free-Admin-Template#7]
Hi,
As you said your template is inside MIT license so can I remove footer from your template and put mine one?

Can I remove this one -> Copyright © 2017 Bootstrap Dash. All rights reserved.
and replace it with -> Copyright © 2017 My Company. All rights reserved.

Thank you.

**Comment by bootstrapdash-team** [comment]
Yes, you can make modifications in the footer
